#coding=utf-8
# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-19 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import model_managers.home_model_manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreationTime', models.DateTimeField(auto_now=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('Name', models.CharField(max_length=255, unique=True)),
                ('IP', models.CharField(max_length=20)),
                ('OS', models.IntegerField()),
                ('Status', models.IntegerField()),
                ('AgentWorkSpace', models.CharField(max_length=255)),
                ('AgentTags', models.CharField(max_length=255)),
                ('AgentPort', models.IntegerField()),
                ('Executors', models.IntegerField(default=0)),
                ('RunningExecutors', models.IntegerField(default=0)),
                ('BuildToolsDir', models.CharField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'agent',
            },
            managers=[
                ('objects', model_managers.home_model_manager.AgentManager()),
            ],
        ),
        migrations.CreateModel(
            name='DicData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DicDataName', models.CharField(max_length=500)),
                ('DicDataValue', models.IntegerField(default=0)),
                ('DicDataDesc', models.CharField(max_length=500, null=True)),
                ('DicDataIsActive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'dicdata',
            },
            managers=[
                ('objects', model_managers.home_model_manager.DicDataManager()),
            ],
        ),
        migrations.CreateModel(
            name='DicType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DicTypeName', models.CharField(max_length=50)),
                ('DicTypeIsActive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'dictype',
            },
            managers=[
                ('objects', model_managers.home_model_manager.DicTypeManager()),
            ],
        ),
        migrations.CreateModel(
            name='ErrorMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ErrorType', models.IntegerField()),
                ('ErrorCode', models.IntegerField()),
                ('ErrorName', models.CharField(max_length=25, null=True)),
                ('ErrorMessage', models.CharField(max_length=100, null=True)),
                ('IsActive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'error_message',
            },
            managers=[
                ('objects', model_managers.home_model_manager.ErrorMessageManager()),
            ],
        ),
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreationTime', models.DateTimeField(auto_now=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('FileName', models.CharField(max_length=255, null=True)),
                ('FileUUID', models.CharField(max_length=50, null=True)),
                ('FilePath', models.CharField(max_length=500, null=True)),
                ('FileType', models.IntegerField()),
                ('FileFolder', models.IntegerField()),
                ('FileSuffixes', models.CharField(max_length=10, null=True)),
                ('FileCreator', models.IntegerField()),
                ('FileSize', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'file_info',
            },
            managers=[
                ('objects', model_managers.home_model_manager.FileManager()),
            ],
        ),
        migrations.CreateModel(
            name='TaskQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskID', models.IntegerField()),
                ('Status', models.IntegerField()),
                ('TaskType', models.IntegerField()),
                ('CaseList', models.CharField(max_length=10000, null=True)),
                ('Priority', models.IntegerField()),
                ('EnqueueTime', models.DateTimeField()),
                ('RerunReportID', models.IntegerField()),
                ('RuntimeEnv', models.IntegerField()),
                ('TaskUUID', models.CharField(max_length=128)),
                ('AgentID', models.IntegerField()),
                ('StartTime', models.DateTimeField(null=True)),
                ('TaskEndTime', models.DateTimeField(null=True)),
                ('FromName', models.CharField(max_length=100, null=True)),
                ('FromIP', models.CharField(max_length=20, null=True)),
                ('Command', models.IntegerField()),
                ('MobileDeviceID', models.IntegerField()),
                ('IsLocked', models.BooleanField(default=False)),
                ('LockTime', models.DateTimeField(null=True)),
                ('DistributeTimes', models.IntegerField()),
                ('ErrorMsg', models.CharField(max_length=255, null=True)),
                ('BuildParameterID', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'task_queue',
            },
            managers=[
                ('objects', model_managers.home_model_manager.TaskQueueManager()),
            ],
        ),
        migrations.CreateModel(
            name='WebApps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreationTime', models.DateTimeField(auto_now=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('app_title', models.CharField(max_length=50)),
                ('app_key', models.CharField(max_length=10)),
                ('app_url', models.CharField(max_length=500)),
                ('app_avatar', models.CharField(max_length=255, null=True)),
                ('app_desc', models.CharField(max_length=500, null=True)),
                ('app_visable_level', models.IntegerField()),
                ('app_creator', models.IntegerField()),
            ],
            options={
                'db_table': 'home_webapps',
            },
            managers=[
                ('objects', model_managers.home_model_manager.WebappManager()),
            ],
        ),
        migrations.AddField(
            model_name='dicdata',
            name='DicType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.DicType'),
        ),
    ]
