#coding=utf-8
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: controller.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='controller.proto',
  package='tutorial',
  syntax='proto3',
  serialized_pb=_b('\n\x10\x63ontroller.proto\x12\x08tutorial\"\x98\x01\n\nController\x12\x0f\n\x07task_id\x18\x01 \x01(\x05\x12\'\n\ttask_type\x18\x02 \x01(\x0e\x32\x14.tutorial.TQTaskType\x12\x11\n\ttask_uuid\x18\x03 \x01(\t\x12\x12\n\ndriver_key\x18\x04 \x01(\t\x12)\n\x0ctask_command\x18\x05 \x01(\x0e\x32\x13.tutorial.TQCommand* \n\tTQCommand\x12\t\n\x05START\x10\x00\x12\x08\n\x04STOP\x10\x01*=\n\nTQTaskType\x12\x10\n\x0c\x41UTOTESTTASK\x10\x00\x12\r\n\tBUILDTASK\x10\x01\x12\x0e\n\nDEPLOYTASK\x10\x02\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_TQCOMMAND = _descriptor.EnumDescriptor(
  name='TQCommand',
  full_name='tutorial.TQCommand',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='START', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STOP', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=185,
  serialized_end=217,
)
_sym_db.RegisterEnumDescriptor(_TQCOMMAND)

TQCommand = enum_type_wrapper.EnumTypeWrapper(_TQCOMMAND)
_TQTASKTYPE = _descriptor.EnumDescriptor(
  name='TQTaskType',
  full_name='tutorial.TQTaskType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='AUTOTESTTASK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BUILDTASK', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEPLOYTASK', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=219,
  serialized_end=280,
)
_sym_db.RegisterEnumDescriptor(_TQTASKTYPE)

TQTaskType = enum_type_wrapper.EnumTypeWrapper(_TQTASKTYPE)
START = 0
STOP = 1
AUTOTESTTASK = 0
BUILDTASK = 1
DEPLOYTASK = 2



_CONTROLLER = _descriptor.Descriptor(
  name='Controller',
  full_name='tutorial.Controller',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='tutorial.Controller.task_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='task_type', full_name='tutorial.Controller.task_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='task_uuid', full_name='tutorial.Controller.task_uuid', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='driver_key', full_name='tutorial.Controller.driver_key', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='task_command', full_name='tutorial.Controller.task_command', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=183,
)

_CONTROLLER.fields_by_name['task_type'].enum_type = _TQTASKTYPE
_CONTROLLER.fields_by_name['task_command'].enum_type = _TQCOMMAND
DESCRIPTOR.message_types_by_name['Controller'] = _CONTROLLER
DESCRIPTOR.enum_types_by_name['TQCommand'] = _TQCOMMAND
DESCRIPTOR.enum_types_by_name['TQTaskType'] = _TQTASKTYPE

Controller = _reflection.GeneratedProtocolMessageType('Controller', (_message.Message,), dict(
  DESCRIPTOR = _CONTROLLER,
  __module__ = 'controller_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.Controller)
  ))
_sym_db.RegisterMessage(Controller)


# @@protoc_insertion_point(module_scope)
