# Generated by Django 2.0 on 2019-02-01 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usergroups',
            table='auth_user_groups_teamcat',
        ),
    ]
