# Generated by Django 2.0 on 2019-02-21 08:08

from django.db import migrations, models
import model_managers.project_model_manager


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreationTime', models.DateTimeField(auto_now_add=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('ProjectID', models.IntegerField()),
                ('Type', models.IntegerField()),
                ('FileID', models.IntegerField()),
                ('Owner', models.IntegerField()),
                ('LockBy', models.IntegerField()),
                ('IsFixed', models.BooleanField()),
            ],
            options={
                'db_table': 'project_document',
            },
            managers=[
                ('objects', model_managers.project_model_manager.ProjectDocumentManager()),
            ],
        )
    ]
