#coding=utf-8
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='agent.proto',
  package='tutorial',
  syntax='proto3',
  serialized_pb=_b('\n\x0b\x61gent.proto\x12\x08tutorial\"b\n\x05\x41gent\x12\x0f\n\x07task_id\x18\x01 \x01(\x05\x12\x11\n\ttask_uuid\x18\x02 \x01(\t\x12$\n\x06result\x18\x03 \x01(\x0e\x32\x14.tutorial.TaskResult\x12\x0f\n\x07message\x18\x04 \x01(\t*#\n\nTaskResult\x12\x08\n\x04\x46\x41IL\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_TASKRESULT = _descriptor.EnumDescriptor(
  name='TaskResult',
  full_name='tutorial.TaskResult',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FAIL', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=125,
  serialized_end=160,
)
_sym_db.RegisterEnumDescriptor(_TASKRESULT)

TaskResult = enum_type_wrapper.EnumTypeWrapper(_TASKRESULT)
FAIL = 0
SUCCESS = 1



_AGENT = _descriptor.Descriptor(
  name='Agent',
  full_name='tutorial.Agent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='tutorial.Agent.task_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='task_uuid', full_name='tutorial.Agent.task_uuid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='result', full_name='tutorial.Agent.result', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='tutorial.Agent.message', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=123,
)

_AGENT.fields_by_name['result'].enum_type = _TASKRESULT
DESCRIPTOR.message_types_by_name['Agent'] = _AGENT
DESCRIPTOR.enum_types_by_name['TaskResult'] = _TASKRESULT

Agent = _reflection.GeneratedProtocolMessageType('Agent', (_message.Message,), dict(
  DESCRIPTOR = _AGENT,
  __module__ = 'agent_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.Agent)
  ))
_sym_db.RegisterMessage(Agent)


# @@protoc_insertion_point(module_scope)
