#coding=utf-8
# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-19 06:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ActionTime', models.DateTimeField(auto_now=True)),
                ('User', models.IntegerField()),
                ('ContentType', models.IntegerField()),
                ('ObjectID', models.CharField(blank=True, max_length=255, null=True)),
                ('ObjectRepr', models.CharField(max_length=200)),
                ('ActionFlag', models.PositiveSmallIntegerField()),
                ('ChangeMessage', models.CharField(blank=True, max_length=255)),
                ('ActionType', models.IntegerField(default=0)),
                ('ProjectID', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'user_action_log',
            },
        ),
        migrations.CreateModel(
            name='User_Extend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(max_length=255, null=True)),
                ('side_bars', models.CharField(max_length=255, null=True)),
                ('dashboard_tools', models.CharField(max_length=255, null=True)),
                ('shortcuts', models.CharField(max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extend_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_user_extend',
            },
        ),
        migrations.CreateModel(
            name='User_Group_Extend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backcolor', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('group_priority', models.IntegerField()),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extend_info', to='auth.Group')),
            ],
            options={
                'db_table': 'auth_group_extend',
            },
        ),
        migrations.CreateModel(
            name='User_Permission_Extend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PermissionType', models.IntegerField()),
                ('Description', models.CharField(max_length=255)),
                ('permission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extend_info', to='auth.Permission')),
            ],
            options={
                'db_table': 'auth_permission_extend',
            },
        ),
        migrations.CreateModel(
            name='UserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_user_groups',
            },
        ),
    ]
