#coding=utf-8
# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-17 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import model_managers.project_model_manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreationTime', models.DateTimeField(auto_now=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('DeviceName', models.CharField(max_length=255)),
                ('RegTime', models.DateTimeField(null=True)),
                ('DeviceID', models.IntegerField()),
                ('AliasName', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'logcat_logger',
            },
            managers=[
                ('objects', model_managers.project_model_manager.TaskManager()),
            ],
        ),
    ]
